write from POSTGRES to Google Sheets
RicSegundo/Ishango_Assessments pull request #97
Opened 2022-07-21 05:20 UTC by oliverangelil

2022-07-21 12:47 UTC, oliverangelil commented
@RicSegundo I pretty much copied this excellent video: https://www.youtube.com/watch?v=4ssigWmExak&ab_channel=LearnGoogleSpreadsheets

There is also [gspread](https://github.com/burnash/gspread) which is a wrapper around the sheets API, but I prefer to directly use the API like in the video. 

Things that need to be improved:
- there is a `creds.json` file in the repo that the API reads to connect to the sheet. I tried to add it as a JSON to github secrets but that threw an error in the deploy workflow (couldn't be passed as an environment variable). Also I recall reading somewhere that JSON should not be passed as a secret. 
- there's no column names in google sheets after writing.

2022-07-21 12:55 UTC, oliverangelil commented
In the cred.json file there is an email address that one must give editor access to in the google sheets
<img width="510" alt="image" src="https://user-images.githubusercontent.com/15682787/180218488-ce6c54f6-0aac-4db5-82dc-b7e36ea23d8e.png">

2022-07-22 00:18 UTC, RicSegundo commented
I'll check asap, in principle this weekend!

2022-07-24 12:20 UTC, oliverangelil commented
https://stackoverflow.com/questions/56277661/is-it-possible-to-store-a-json-file-to-an-env-variable-with-dotenv
https://stackoverflow.com/questions/71544103/how-can-we-store-a-json-credential-to-env-variable-in-python

2022-07-26 19:35 UTC, oliverangelil commented
@RicSegundo I solved 2 of the 3 "areas for improvement" listed above:
- pass the json through github secrets as base64, and then decode back to json on the VM
- write the column names to google sheets

Hope you can support on the last bullet (the general design of the code). Also need to add type hinting...

2022-07-27 08:36 UTC, oliverangelil commented
I have removed `sonar-project.properties` files and replaced it with `.sonarcloud.properties`. `sonar-project.properties` is only used for the CI approach but we're using the automatic approach (recommended)

2022-08-03 14:16 UTC, RicSegundo requested changes

2022-08-03 14:16 UTC, RicSegundo commented on src/scraping/results.py
> +        db = T.DataBaseInteraction()
I think that properties of the object should be passed at the time of creation of the object, and not when you call the method (and then it saves to self.something)

2022-08-03 14:16 UTC, RicSegundo commented on src/scraping/tools.py
> +from googleapiclient.discovery import build
import the whole namespace, and call build from it below

2022-08-03 14:16 UTC, RicSegundo commented on src/scraping/tools.py
> +    def __init__(self) -> None:
re-add data frame and table_name, and set dataframe to  = None so it is not mandatory to pass when instantiating the object

2022-08-03 14:16 UTC, RicSegundo commented on src/scraping/tools.py
> +        self.db_engine: sqlalchemy.engine.base.Engine = None,
change the order of these 2 lines because I am OCD

2022-08-03 14:16 UTC, RicSegundo commented on src/scraping/tools.py
> +        dataframe: pd.DataFrame,
remove this as unnecessary now

2022-08-03 14:16 UTC, RicSegundo commented on src/scraping/tools.py
> +        self.dataframe = dataframe
remove as unnecessary

2022-08-03 14:16 UTC, RicSegundo commented on src/scraping/tools.py
> +        decodedbytes: bytes = base64.b64decode(b64[1:-1])
I'll send the link to the named ranges and list slicing, e.g. https://www.w3schools.com/python/ref_func_slice.asp

2022-08-03 14:16 UTC, RicSegundo commented on src/scraping/tools.py
> +        df: pd.DataFrame = pd.read_sql(table_name, con=self.db_engine)
maybe create another method that process the data?

2022-08-03 14:16 UTC, RicSegundo commented on src/scraping/tools.py
> +        df: pd.DataFrame = pd.read_sql(table_name, con=self.db_engine)
@oliverangelil had the great idea of checking the column type and making it automatic to change the date formats

2022-08-03 14:16 UTC, RicSegundo commented on src/scraping/tools.py
> +        data.insert(0, column_names)
maybe give a name to the 0, so we know what it is? put it in a variable?

2022-08-03 14:16 UTC, RicSegundo commented on src/scraping/tools.py
> +        data.insert(0, column_names)
maybe you can put data = column_names (already as a list of lists with only 1 list) + data

2022-08-03 14:16 UTC, RicSegundo commented on src/scraping/tools.py
> +            range="test!A1",
maybe divide this into 3 actions and not cascade them?

2022-08-03 14:16 UTC, RicSegundo commented on src/scraping/tools.py
> +        creds = service_account.Credentials.from_service_account_info(json_dict, scopes=SCOPES)
add the correct name spacing here

2022-08-03 14:16 UTC, RicSegundo commented on src/scraping/tools.py
> +        data.insert(0, column_names)
(maybe add this to the data pre-processing)?

2022-08-03 14:16 UTC, RicSegundo commented on src/scraping/tools.py
> +            range="test!A1",
and I know you know, write all the constants into the definition files
(every time I see literal string text here a dolphin dies)

2022-08-05 15:13 UTC, oliverangelil commented
@RicSegundo, the code works perfectly, but there is a mypy issue that I cannot resolve. 
It complains about this line:
`super()._DataBaseInteraction__db_connect()`

This SO question explains the syntax:
https://stackoverflow.com/a/20261595/5392289

2022-08-06 13:00 UTC, oliverangelil commented
@RicSegundo it should be protected. I've fixed it. You can approve.
https://stackoverflow.com/a/12784107/5392289

2022-08-06 15:13 UTC, RicSegundo approved these changes

2022-08-06 15:13 UTC, merged